const Icons = {
  phone: require("../assets/images/project/default.png"),
  mark: require("../assets/images/project/Frame (1).png"),
  eyeClosed: require("../assets/images/project/Frame 4.png"),
  charge: require("../assets/images/project/Frame 379 (5).png"),
  phone2: require("../assets/images/project/Frame 466.png"),
  network: require("../assets/images/project/Frame 469 (1).png"),
  sync: require("../assets/images/project/Frame 478.png"),
  education: require("../assets/images/project/Frame 481.png"),
  tick: require("../assets/images/project/Frame 484 (1).png"),
  cart: require("../assets/images/project/Frame 484.png"),
  wallet: require("../assets/images/project/Frame 487.png"),
  reverse: require("../assets/images/project/Frame.png"),
  greenCheck: require("../assets/images/project/green check (1).png"),
  caution: require("../assets/images/project/green check.png"),
  dot: require("../assets/images/project/Group (1).png"),
  wema: require("../assets/images/project/Group (2).png"),
  square: require("../assets/images/project/Group (3).png"),
  user: require("../assets/images/project/Group.png"),
  date: require("../assets/images/project/Group 39.png"),
  blueBin: require("../assets/images/project/Icons (1).png"),
  transfer: require("../assets/images/project/icons (3).png"),
  blueUser: require("../assets/images/project/Layer_1 (2).png"),
  bell: require("../assets/images/project/Layer_1 (3).png"),
  whiteWatsapp: require("../assets/images/project/Layer_1.png"),
  post: require("../assets/images/project/Union.png"),
  dollar: require("../assets/images/project/Vector (1).png"),
    transferUp: require("../assets/images/project/Vector (2).png"),
    camera: require("../assets/images/project/Vector (3).png"),
    twitter: require("../assets/images/project/Vector (4).png"),
    line: require("../assets/images/project/Vector 8.png"),
  cancel: require("../assets/images/project/Vector.png"),
  home:require("../assets/images/project/navigation/home.png"),
  shop:require("../assets/images/project/navigation/Shop.png"),
  walletIcon:require("../assets/images/project/navigation/wallet.png")
};
export default Icons;