import { goBack } from "expo-router/build/global-state/routing";

const Images = {
  Bluearrow: require("../assets/images/project/bluearrow.png"),
  goBack: require("../assets/images/project/goBack.png"),
  icon: require("../assets/images/project/logo.png"),
  slide1: require("../assets/images/project/Slide1.png"),
  slide2: require("../assets/images/project/slide2.png"),
  slide3: require("../assets/images/project/slide3.png"),
  caution: require("../assets/images/project/caution.png"),
  cp: require("../assets/images/project/cp.png"),
  questionMark: require("../assets/images/project/_.png"),
  email: require("../assets/images/project/8-Email.png"),
  contact: require("../assets/images/project/basil_contacts-solid.png"),
  budpay: require("../assets/images/project/BudPay-Logo3 1.png"),
  calendar: require("../assets/images/project/calendar.png"),
  chat: require("../assets/images/project/chat.png"),
  glo: require("../assets/images/project/Clip path group.png"),
  phd: require("../assets/images/project/Ellipse 16 (1).png"),
  edc: require("../assets/images/project/Ellipse 16 (5).png"),
  dstv: require("../assets/images/project/Ellipse 17 (1).png"),
  aedc: require("../assets/images/project/Ellipse 16.png"),
  ibedc: require("../assets/images/project/Ellipse 17.png"),
  trash: require("../assets/images/project/Flat.png"),
  flutterwave: require("../assets/images/project/Flutterwave_Logo 1.png"),
  fire: require("../assets/images/project/Frame 379 (1).png"),
  netflix: require("../assets/images/project/Frame 379 (2).png"),
  prime: require("../assets/images/project/Frame 379 (3).png"),
  starTimes: require("../assets/images/project/Frame 379 (4).png"),
  jos: require("../assets/images/project/Frame 379.png"),
  moniepoint: require("../assets/images/project/Subtract.png"),
  WemaLogo: require("../assets/images/project/Group (2).png"),
  SterLogo: require("../assets/images/project/Group (1).png"),
  PremLogo: require("../assets/images/project/Group (3).png"),
  MonieLogo: require("../assets/images/project/Group (4).png"),
  arrowC: require("../assets/images/project/Group (5).png"),
  instagram: require("../assets/images/project/Group (6).png"),
  whatsApp: require("../assets/images/project/Group (7).png"),
  Gmail: require("../assets/images/project/Group (8).png"),
  MTN: require("../assets/images/project/Group 29.png"),
  nineMobile: require("../assets/images/project/Group 30.png"),
  finger: require("../assets/images/project/Group 45.png"),
  X: require("../assets/images/project/Group 50.png"),
  buyData: require("../assets/images/project/HONOUR SLIDE5 1.png"),
  paystack: require("../assets/images/project/image 1.png"),
  jamb: require("../assets/images/project/JAMB-Logo 1 (1).png"),
  neco: require("../assets/images/project/JAMB-Logo 1.png"),
  emoji: require("../assets/images/project/Layer_1 (1).png"),
  arrowIn: require("../assets/images/project/Layer_1 (4).png"),
  fingerPrint: require("../assets/images/project/material-symbols_fingerprint.png"),
  airtel: require("../assets/images/project/path4042.png"),
  thumbsUp: require("../assets/images/project/Thumbs Up.png"),
  waec: require("../assets/images/project/Waec_logo 1.png"),
  check: require("../assets/images/project/XMLID_1_.png"),
  profile: require("../assets/images/project/Profile.jpg"),
  PersonIcon: require("../assets/images/project/Group.png"),
  wallet: require("../assets/images/project/Wallet.png"),
  logo: require("../assets/images/project/logo.png"),
  wemacard: require("../assets/images/project/wemacard.png"),
  premcard: require("../assets/images/project/premcard.png"),
  stercard: require("../assets/images/project/stercard.png"),
  moniecard: require("../assets/images/project/moniecard.png"),
};
export default Images;